'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _reduxsauce = require('reduxsauce');

exports.default = (0, _reduxsauce.createTypes)('\n\n  GET_USERS_REQUEST\n  GET_USERS_SUCCESS\n  GET_USERS_FAILURE\n\n  UPDATE_USERS_REQUEST\n  UPDATE_USERS_SUCCESS\n  UPDATE_USERS_FAILURE\n\n  GET_USER_STATUS_REQUEST\n  GET_USER_STATUS_SUCCESS\n  GET_USER_STATUS_FAILURE\n\n  GET_USER_META_REQUEST\n  GET_USER_META_SUCCESS\n  GET_USER_META_FAILURE\n\n  GET_MEETME_REQUEST\n  GET_MEETME_SUCCESS\n  GET_MEETME_FAILURE\n\n  GET_RATEPHOTO_REQUEST\n  GET_RATEPHOTO_SUCCESS\n  GET_RATEPHOTO_FAILURE\n\n  ADD_USER_META_REQUEST\n  ADD_USER_META_FAILURE\n\n'); // A list of all actions in the system.